---
title: "20180528_5.2节KNN"
author: "wzy"
date: "2018年5月28日"
output: html_document
---

```{r}
knitr::opts_chunk$set(
  fig.width = 9,
  fig.height = 6
)
```


```{r}
library(ggplot2)
library(TFTSA)
```


## 1. 读取数据

```{r}
setwd("D:/R/packages/TFTSA")
tmlzzloess <- read.csv("data-raw/tmlzzloess.csv")
tmlzznew <- read.csv("data-raw/tmlzznew.csv",header = T)

rownames(tmlzzloess) <- tmlzzloess[,1]
tmlzzloess <- tmlzzloess[,-1]
rownames(tmlzznew) <- tmlzznew[,1]
tmlzznew <- tmlzznew[,-1]
```

## 2. 设定object flow和flow database

### 2.1 将flow database设为原始数据

```{r}
tmlobj <- tmlzznew[6,]
tmlbase <- tmlzznew[-6,]
```

```{r}
pre1006 <- TFTSA::flow_knn(tmlobj,tmlbase,start = 73,k = 3,lag_duration = 24,fore_duration = 12)
```

不必要的波动很大，这种微小波动可能没用。

```{r}
tml1006both <- rbind(tmlobj,pre1006)
tml1006both <- t(tml1006both)
tml1006both <- as.data.frame(tml1006both)
```

```{r}
ggplot(tml1006both,aes(1:288,tml1006both$`06-10月-16`))+geom_point(colour="steelblue")+
  geom_line(aes(1:288,tml1006both$`06-10月-161`),colour="red",size=1)+
  xlab("时间序号")+ylab("车流量")+scale_color_hue("日期")+
  scale_x_continuous(breaks = seq(0,288,24))+
  scale_y_continuous(breaks = seq(0,120,20))
```



### 2.2 将flow database设为LOESS后的数据

```{r}
tmlobj <- tmlzznew[6,]
tmlbase <- tmlzzloess[-6,]
```

```{r}
pre1006 <- TFTSA::flow_knn(tmlobj,tmlbase,start = 73,k = 3,lag_duration = 24,fore_duration = 12)
```


```{r}
tml1006both <- rbind(tmlobj,pre1006)
tml1006both <- t(tml1006both)
tml1006both <- as.data.frame(tml1006both)
```

```{r}
ggplot(tml1006both,aes(1:288,tml1006both$`06-10月-16`))+geom_point(colour="steelblue")+
  geom_line(aes(1:288,tml1006both$`06-10月-161`),colour="red",size=1)+
  xlab("时间序号")+ylab("车流量")+scale_color_hue("日期")+
  scale_x_continuous(breaks = seq(0,288,24))+
  scale_y_continuous(breaks = seq(0,120,20))
```

可以看到除了不光滑外，预测效果整体良好。就是对于高峰值预测偏低。

## 3. 残差分析

### 3.1 0均值性

```{r}
res1006 <- tmlobj[73:288] - pre1006[73:288]
plot(73:288,res1006)
abline(h=0)
```

### 3.2 正态性

```{r}
qqnorm(res1006)
qqline(res1006)
```

### 3.3 自相关性

```{r}
res1006 <- as.numeric(res1006)
acf(res1006)
```

### 3.4 纯随机性

```{r}
Box.test(res1006)
```

## 4. 参数的灵敏度分析

### 4.1 关于k的灵敏度分析

```{r}
pre1006_k5 <- flow_knn(tmlobj,tmlbase,start = 73,k = 5,lag_duration = 24,fore_duration = 12)
```

```{r}
flow_forecastplot(tmlobj,pre1006_k5)
```


### 4.2 关于lag_duration的灵敏度分析

#### 4.2.1 ld36

```{r}
pre1006_ld36 <- flow_knn(tmlobj,tmlbase,start = 73,k = 3,lag_duration = 36,fore_duration = 12)
```

```{r}
flow_forecastplot(tmlobj,pre1006_ld36)
```

#### 4.2.2 ld48

```{r}
pre1006_ld48 <- flow_knn(tmlobj,tmlbase,start = 73,k = 3,lag_duration = 24,fore_duration = 12)
```

```{r}
flow_forecastplot(tmlobj,pre1006_ld48)
```

### 4.3 关于fore_duration的灵敏度分析

#### 4.3.1 fd6

```{r}
pre1006_fd6 <- flow_knn(tmlobj,tmlbase,start = 73,k = 3,lag_duration = 24,fore_duration = 6)
```

```{r}
flow_forecastplot(tmlobj,pre1006_fd6)
```

#### 4.3.2 fd4

```{r}
pre1006_fd4 <- flow_knn(tmlobj,tmlbase,start = 73,k = 3,lag_duration = 24,fore_duration = 4)
```

```{r}
flow_forecastplot(tmlobj,pre1006_fd4)
```

#### 4.3.3 fd2

```{r}
pre1006_fd2 <- flow_knn(tmlobj,tmlbase,start = 73,k = 3,lag_duration = 24,fore_duration = 2)
```

```{r}
flow_forecastplot(tmlobj,pre1006_fd2)
```

